export enum StatusOS {
  RECEBIDA = 'RECEBIDA',
  EM_DIAGNOSTICO = 'EM_DIAGNOSTICO',
  AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO',
  EM_EXECUCAO = 'EM_EXECUCAO',
  FINALIZADA = 'FINALIZADA',
  ENTREGUE = 'ENTREGUE',
}

export const transicoesValidas: Record<StatusOS, StatusOS | null> = {
  [StatusOS.RECEBIDA]: StatusOS.EM_DIAGNOSTICO,
  [StatusOS.EM_DIAGNOSTICO]: StatusOS.AGUARDANDO_APROVACAO,
  [StatusOS.AGUARDANDO_APROVACAO]: StatusOS.EM_EXECUCAO,
  [StatusOS.EM_EXECUCAO]: StatusOS.FINALIZADA,
  [StatusOS.FINALIZADA]: StatusOS.ENTREGUE,
  [StatusOS.ENTREGUE]: null,
};
