apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
data:
  NODE_ENV: "production"
  PORT: "3000"
  POSTGRES_DB: "oficina_db"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_FROM: "Oficina Sistema <oficina@sistema.com>"
  APP_URL: "http://localhost:3000"
  JWT_EXPIRES_IN: "1d"
  WEBHOOK_TOKEN_EXPIRES_IN: "15m"
