apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: oficina
type: Opaque
stringData:
  DATABASE_URL: "postgresql://oficina_user:senha_segura@postgres-service:5432/oficina_db"
  POSTGRES_USER: "oficina_user"
  POSTGRES_PASSWORD: "senha_segura"
  JWT_SECRET: "seu-segredo-forte-com-pelo-menos-32-caracteres"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD_HASH: "$2b$10$hash_bcrypt_aqui"
  WEBHOOK_SECRET: "segredo-para-tokens-de-webhook-com-32-caracteres"
  MAIL_USER: "seu@email.com"
  MAIL_PASS: "app-password-aqui"
